language: node_js
node_js:
  - "0.12"

services:
  - rabbitmq

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_script:
  - cd server && npm run codeclimate && npm run coveralls
